# Numpy Introduction

In [ ]:
 
#  pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
# import numpy library check its version
import numpy as np
print(np.__version__)


1.26.4


In [2]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [3]:
a = np.arange(6)
print(a)
# how i can check the shape of array
a.shape

[0 1 2 3 4 5]


(6,)

In [4]:
a2 = a[np.newaxis, :]
print(a2)
# check the shape of a2
a2.shape

[[0 1 2 3 4 5]]


(1, 6)

In [5]:
a2 = a[:, np.newaxis]
print(a2)
# check the shape of a2
a2.shape

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


(6, 1)

# 3D Array


In [6]:
# create a3 by adding new axis to a and check its shape
a3 = a[np.newaxis, np.newaxis, :]
print(a3)
a3.shape

[[[0 1 2 3 4 5]]]


(1, 1, 6)

In [17]:
# make a3 by adding new axis to a2 and check its shape
a3 = a2[np.newaxis, :]
print(a3)

a3.shape

[[[0]
  [1]
  [2]
  [3]
  [4]
  [5]]]


(1, 6, 1)

# Assigmment :
why do we have  1D , 2D, or 3D arrays and where we need them in data science?

# Creating Arrays with Numpy

In [19]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([(7, 8, 9, 10, 11, 12),(13, 14, 15, 16, 17, 18)])

In [41]:
# types of arrays
type(a)

numpy.ndarray

In [42]:
type(b)

numpy.ndarray

In [ ]:
# how i can check the data type of arrays elements
a.dtype

dtype('int64')

In [ ]:
# how i can check the data types of arrays elements
b.dtype

dtype('int64')

In [24]:

print(a)
a.shape

[1 2 3 4 5 6]


(6,)

In [22]:
print(b)
b.shape

[[ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


(2, 6)

# initize Arrays

In [ ]:
zeros = np.zeros((3, 3)) # (rows, columns) 
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
zeros.dtype

dtype('float64')

In [28]:
ones = np.ones((3,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [35]:
ones.dtype

dtype('float64')

In [29]:
full = np.full((2,3), 7)
print(full)

[[7 7 7]
 [7 7 7]]


In [39]:
full.dtype

dtype('float64')

In [37]:
full = np.full((2,3), 7.5)
print(full)

[[7.5 7.5 7.5]
 [7.5 7.5 7.5]]


In [38]:
full.dtype

dtype('float64')

In [31]:
# Identity matrix
identity = np.eye(5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
identity.dtype

dtype('float64')

# Attribute of the Arrays

In [43]:
a.shape

(6,)

In [ ]:
# Show the length of arrays/mtrix
len(a)


6

In [45]:
# check the dimensions of arrays/matrix
a.ndim

1

In [46]:
b.ndim  

2

In [47]:
# Size of arrays/matrix mean the total number of elements in arrays/matrix
a.size

6

In [48]:
identity.size

25

# Basic Operations

In [50]:
a

array([1, 2, 3, 4, 5, 6])

In [51]:
b

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

# subtraction

In [52]:
g = a - b
g

array([[ -6,  -6,  -6,  -6,  -6,  -6],
       [-12, -12, -12, -12, -12, -12]])

In [53]:
g =  b - a
g

array([[ 6,  6,  6,  6,  6,  6],
       [12, 12, 12, 12, 12, 12]])

# Addition

In [54]:
g = a + b
g

array([[ 8, 10, 12, 14, 16, 18],
       [14, 16, 18, 20, 22, 24]])

In [55]:
# Another way to add two arrays is by using np.add() function
add = np.add(a, b)
add

array([[ 8, 10, 12, 14, 16, 18],
       [14, 16, 18, 20, 22, 24]])

# Multiplication

In [56]:
g = a * b
g

array([[  7,  16,  27,  40,  55,  72],
       [ 13,  28,  45,  64,  85, 108]])

# Division

In [57]:
g = a / b
g

array([[0.14285714, 0.25      , 0.33333333, 0.4       , 0.45454545,
        0.5       ],
       [0.07692308, 0.14285714, 0.2       , 0.25      , 0.29411765,
        0.33333333]])

# Square of each element

In [58]:
a

array([1, 2, 3, 4, 5, 6])

In [59]:
k = a ** 2
k

array([ 1,  4,  9, 16, 25, 36])

In [ ]:
# if we want to multiply all the elements of array a by 3 we can do it like this
i  = a * 3
i

array([ 3,  6,  9, 12, 15, 18])