# Numpy Indexing and Slicing

In [1]:
import numpy as np


In [2]:
# create an array

a = np.array([1, 2, 3, 4, 5, 6, 7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# indexing

#a[1]  # 2
#a[-1]  # 7
# a[-2]  # 6


np.int64(7)

In [12]:
# slicing
a[0:]
a[0: 5]
a[3: 6]

array([4, 5, 6])

In [5]:
b = np.arange(0, 12, 2)
b

array([ 0,  2,  4,  6,  8, 10])

In [6]:
b[2]

np.int64(4)

In [8]:
c = b.reshape(2,3)
c

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [9]:
c[0]

array([0, 2, 4])

In [14]:
d = b.reshape(3,2)
d

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [15]:
d[0]

array([0, 2])

In [ ]:
# multi conditions
c[c < 5 ]


array([0, 2, 4])

# enlist boolean operators conditional operators