# Numpy Indexing and Slicing

In [1]:
import numpy as np


In [2]:
# create an array

a = np.array([1, 2, 3, 4, 5, 6, 7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# indexing

#a[1]  # 2
#a[-1]  # 7
# a[-2]  # 6


np.int64(7)

In [12]:
# slicing
a[0:]
a[0: 5]
a[3: 6]

array([4, 5, 6])

In [5]:
b = np.arange(0, 12, 2)
b

array([ 0,  2,  4,  6,  8, 10])

In [6]:
b[2]

np.int64(4)

In [8]:
c = b.reshape(2,3)
c

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [9]:
c[0]

array([0, 2, 4])

In [14]:
d = b.reshape(3,2)
d

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [15]:
d[0]

array([0, 2])

In [ ]:
# multi conditions
c[c < 5 ]


array([0, 2, 4])

# Enlist boolean operators conditional operators
| Operator | Meaning                  | Example  |
| -------- | ------------------------ | -------- |
| `==`     | Equal to                 | `a == b` |
| `!=`     | Not equal to             | `a != b` |
| `>`      | Greater than             | `a > b`  |
| `<`      | Less than                | `a < b`  |
| `>=`     | Greater than or equal to | `a >= b` |
| `<=`     | Less than or equal to    | `a <= b` |


---
# Making an array from a data or another array

In [22]:
a = np.arange(0 , 222, 5)
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220])

In [23]:
len(a)

45

In [25]:
array1 = a[40 :45]
array1

array([200, 205, 210, 215, 220])

In [26]:
# stack the arrays

a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [ ]:
# vertically stack the arrays
v = np.vstack((a1 , a2))
v

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [28]:
# Horizontally stack the arrays
h = np.hstack((a1 , a2))
h

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

# # Split the arrays into 2D , 3D and upto so on


In [32]:
arr = np.arange(1 , 25 )
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
# split the arrays into 2D array

np.split(arr, 2)

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])]

In [30]:
# split the arrays
arr = np.arange(1 , 25 )
arr.reshape(2,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
# split the 2D array into three equal shape arrays

np.split(arr, 3)

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])]

In [34]:
np.hsplit(arr, (3, 4))

[array([1, 2, 3]),
 array([4]),
 array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
        22, 23, 24])]