# Numpy Indexing and Slicing

In [1]:
import numpy as np


In [2]:
# create an array

a = np.array([1, 2, 3, 4, 5, 6, 7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# indexing

#a[1]  # 2
#a[-1]  # 7
# a[-2]  # 6


np.int64(7)

In [12]:
# slicing
a[0:]
a[0: 5]
a[3: 6]

array([4, 5, 6])

In [5]:
b = np.arange(0, 12, 2)
b

array([ 0,  2,  4,  6,  8, 10])

In [6]:
b[2]

np.int64(4)

In [8]:
c = b.reshape(2,3)
c

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [9]:
c[0]

array([0, 2, 4])

In [14]:
d = b.reshape(3,2)
d

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [15]:
d[0]

array([0, 2])

In [ ]:
# multi conditions
c[c < 5 ]


array([0, 2, 4])

# Enlist boolean operators conditional operators
| Operator | Meaning                  | Example  |
| -------- | ------------------------ | -------- |
| `==`     | Equal to                 | `a == b` |
| `!=`     | Not equal to             | `a != b` |
| `>`      | Greater than             | `a > b`  |
| `<`      | Less than                | `a < b`  |
| `>=`     | Greater than or equal to | `a >= b` |
| `<=`     | Less than or equal to    | `a <= b` |


---
# Making an array from a data or another array

In [22]:
a = np.arange(0 , 222, 5)
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220])

In [23]:
len(a)

45

In [25]:
array1 = a[40 :45]
array1

array([200, 205, 210, 215, 220])

In [26]:
# stack the arrays

a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [ ]:
# vertically stack the arrays
v = np.vstack((a1 , a2))
v

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [28]:
# Horizontally stack the arrays
h = np.hstack((a1 , a2))
h

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

# # Split the arrays into 2D , 3D and upto so on


In [32]:
arr = np.arange(1 , 25 )
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
# split the arrays into 2D array

np.split(arr, 2)

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])]

In [30]:
# split the arrays
arr = np.arange(1 , 25 )
arr.reshape(2,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
# split the 2D array into three equal shape arrays

np.split(arr, 3)

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])]

In [34]:
np.hsplit(arr, (3, 4))

[array([1, 2, 3]),
 array([4]),
 array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
        22, 23, 24])]

---
# Matix Or Matrices

In [ ]:
# creating a '2 by 3 ' mtrix
a = np.array([[1, 2, 3], [4, 5, 6]])
a


array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
a[1]

array([4, 5, 6])

In [40]:
# create a matrix of big dimension
b = np.arange(0, 100, 2).reshape(5 , 10)
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [42]:
# slicing a matrix 
b[:,:] # means the all the rows and ll the columns 

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [43]:
# slicing a matrix 

c = b[1:3, 3:5] # 1:3 deine the eange of the matrix and 3:5 define the range the columns

In [55]:
# sum the matrix all values
b.sum()

np.int64(2450)

In [53]:
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [ ]:
# check the maximum value from th matrix
b.max()


np.int64(98)

In [ ]:
# show the max row
b.max(axis=0)


array([80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [ ]:
# show the highest columns
b.max(axis=1)


array([18, 38, 58, 78, 98])

In [54]:
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [45]:
# check the minimum value from th matrix
b.min()

np.int64(0)

In [ ]:
# show the minimum complete row
b.min(axis=0)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# show the minimum complete column

b.min(axis=1)

array([ 0, 20, 40, 60, 80])

In [58]:
m = np.arange(0 ,20 ,2).reshape(5,2)
m

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [59]:
m + np.array([20, 22])

array([[20, 24],
       [24, 28],
       [28, 32],
       [32, 36],
       [36, 40]])

In [61]:
m * np.array([20, 22])

array([[  0,  44],
       [ 80, 132],
       [160, 220],
       [240, 308],
       [320, 396]])

In [62]:
m - np.array([20, 22])

array([[-20, -20],
       [-16, -16],
       [-12, -12],
       [ -8,  -8],
       [ -4,  -4]])

In [63]:
m / np.array([20, 22])

array([[0.        , 0.09090909],
       [0.2       , 0.27272727],
       [0.4       , 0.45454545],
       [0.6       , 0.63636364],
       [0.8       , 0.81818182]])

In [64]:
m % np.array([20, 22])

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [60]:
np.vstack((m, np.array([42,44])))

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [42, 44]])

In [65]:
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [67]:
# Reverse the matrix 
np.flip(b)

array([[98, 96, 94, 92, 90, 88, 86, 84, 82, 80],
       [78, 76, 74, 72, 70, 68, 66, 64, 62, 60],
       [58, 56, 54, 52, 50, 48, 46, 44, 42, 40],
       [38, 36, 34, 32, 30, 28, 26, 24, 22, 20],
       [18, 16, 14, 12, 10,  8,  6,  4,  2,  0]])